
-- SECUENCIA PARA TBLNEJAR LA PK DE LA TABLA TBL_CIUDAD
CREATE SEQUENCE SEQ_TBL_CIUDAD
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_CIUDAD OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_CIUDAD IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_CIUDAD';


-- SECUENCIA PARA TBLNEJAR LA PK DE LA TABLA TBL_PERSONA
CREATE SEQUENCE SEQ_TBL_PERSONA
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_PERSONA OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_PERSONA IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_PERSONA';



-- SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_ARTICULO
CREATE SEQUENCE SEQ_TBL_ARTICULO
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_ARTICULO OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_ARTICULO IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_ARTICULO';

-- SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_CLIENTE
CREATE SEQUENCE SEQ_TBL_CLIENTE
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_CLIENTE OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_CLIENTE IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_CLIENTE';

-- SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_ENC_FACTURA
CREATE SEQUENCE SEQ_TBL_ENC_FACTURA
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_ENC_FACTURA OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_ENC_FACTURA IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_ENC_FACTURA';


-- SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_DET_FACTURA
CREATE SEQUENCE SEQ_TBL_DET_FACTURA
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_DET_FACTURA OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_DET_FACTURA IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_DET_FACTURA';

