
CREATE TABLE TBL_DET_FACTURA
(
  CODIGO 		  		INTEGER  PRIMARY KEY DEFAULT NEXTVAL('SEQ_TBL_DET_FACTURA'),
  CODIGO_FACTURA      			INTEGER,
  PRECIO_VENTA				NUMERIC(20,0),
  DESCUENTO				NUMERIC(20,0),
  CODIGO_ARTICULO			INTEGER,
  CANTIDAD				INTEGER
 );

 ALTER TABLE TBL_DET_FACTURA ADD CONSTRAINT FK_TBL_ENC_FACTURA FOREIGN KEY (CODIGO) REFERENCES TBL_ENC_FACTURA (CODIGO);
 ALTER TABLE TBL_DET_FACTURA ADD CONSTRAINT FK_TBL_ARTICULO FOREIGN KEY (CODIGO_ARTICULO) REFERENCES TBL_ARTICULO (CODIGO);