
-- SECUENCIA PARA TBLNEJAR LA PK DE LA TABLA TBL_CIUDAD
CREATE SEQUENCE SEQ_TBL_CIUDAD
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_CIUDAD OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_CIUDAD IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_CIUDAD';


-- SECUENCIA PARA TBLNEJAR LA PK DE LA TABLA TBL_PERSONA
CREATE SEQUENCE SEQ_TBL_PERSONA
   INCREMENT 1
   START 1
   MINVALUE 1
   MAXVALUE 999999999999999999;
ALTER SEQUENCE SEQ_TBL_PERSONA OWNER TO postgres;
COMMENT ON SEQUENCE SEQ_TBL_PERSONA IS 'SECUENCIA PARA MANEJAR LA PK DE LA TABLA TBL_PERSONA';