		
CREATE TABLE TBL_PERSONA
(
  CDPERSONA 		  		INTEGER  PRIMARY KEY DEFAULT NEXTVAL('SEQ_TBL_PERSONA'),
  STRNOMBRES      			CHARACTER VARYING(30),
  STRAPELLIDOS 				CHARACTER VARYING(30),
  NMDOCUMENTO 				NUMERIC(10,0),
  STRDIRECCION 				CHARACTER VARYING(50),
  STRTELEFONO1 				CHARACTER VARYING(30),
  STRCELULAR 		   		CHARACTER VARYING(30),
  STREMAIL 			  		CHARACTER VARYING(50),
  DTYPE 			       	CHARACTER VARYING(5),
  FEPROCESO 		    	TIMESTAMP WITH TIME ZONE,
  STRTIPODOCUMENTO 			CHARACTER VARYING(4),
  STRNATURALEZA 			CHARACTER VARYING(5),
  STRDIGITOVERIFICACION 	CHARACTER VARYING(3),
  PROPIETARIO 				BOOLEAN,
  TERCERO 					BOOLEAN,
  FEMODIFICA 				TIMESTAMP WITHOUT TIME ZONE,
  INQUILINO 				BOOLEAN,
  EMPLEADO 					BOOLEAN DEFAULT FALSE,
  GENERO 					CHARACTER VARYING(1),
  CUENTACOBRO 				NUMERIC(18,0),
  USUARIOINGRESO 			CHARACTER VARYING(50),
  USUARIOMODIFICA 			CHARACTER VARYING(50),
  TELOFICINA 				CHARACTER VARYING(25),
  SEGUNDONOMBRE 			CHARACTER VARYING(50),
  SEGUNDOAPELLIDO 			CHARACTER VARYING(50),
  CIUDAD_EXPEDICION_DCTO	INTEGER,
  FECHANACIMIENTO 			DATE,
  CIUDADNACIMIENTO 			INTEGER
 );
 
 ALTER TABLE TBL_PERSONA ADD CONSTRAINT FK_CIUDAD_EXPEDICION_DCTO FOREIGN KEY (CIUDAD_EXPEDICION_DCTO) REFERENCES TBL_CIUDAD (CODIGO);
 ALTER TABLE TBL_PERSONA ADD CONSTRAINT FK_CIUDAD_NACIMIENTO FOREIGN KEY (CIUDADNACIMIENTO) REFERENCES TBL_CIUDAD (CODIGO);
 ALTER TABLE TBL_PERSONA ADD CONSTRAINT UK_DOCUMENTO_IDENTIDAD UNIQUE(NMDOCUMENTO);